language: python
os: linux
dist: xenial

before_install:
    - export TZ='Asia/Shanghai'  # 设置时区

git:
    depth: 1

install:
    - wget https://github.com/gohugoio/hugo/releases/download/v0.67.1/hugo_0.67.1_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb

script:
    - hugo version
    - hugo

deploy:
    strategy: git
    provider: pages
    skip_cleanup: true
    token: $token
    on:
        branch: hugo
    local_dir: public
    email: lijwxg@hotmail.com
    name: Travis CI
    target_branch: master
